import {
  FarmerProfile,
  OfficerProfile,
  FieldRecord,
  CropRecord,
  EvidenceRecord,
  DisasterReport,
  ClaimRecord,
} from "../types";

export const initialFarmerProfile: FarmerProfile = {
  id: "FMR001",
  name: "Ramesh Kumar",
  phone: "+91 98765 43210",
  email: "ramesh.kumar@agrimail.in",
  village: "Kankipadu",
  district: "Krishna",
  state: "Andhra Pradesh",
  preferredLanguage: "en",
  aadharLastFour: "8942",
  insuranceInfo: {
    policyNumber: "PMFBY/AP/2026/094281",
    schemeName: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    sumInsuredPerAcre: 30000,
    insurerName: "Agriculture Insurance Company of India (AIC)",
    coverageStartDate: "2026-06-01",
    coverageEndDate: "2026-12-31",
    applicationId: "APP-PMFBY-88319",
  },
};

export const initialOfficerProfile: OfficerProfile = {
  uid: "off-demo-uid",
  id: "OFF-704",
  name: "Dr. Ananya Sharma",
  badgeNumber: "AIC-AP-KR-042",
  email: "ananya.sharma@aicofindia.gov.in",
  role: "officer",
  officerId: "AIC-AP-KR-042",
  district: "Krishna",
  assignedDistrict: "Krishna",
  insurerName: "Agriculture Insurance Company of India",
};

// Krishna District agricultural coordinates (Kankipadu agricultural basin)
export const initialFields: FieldRecord[] = [
  {
    id: "FL001",
    farmerId: "FMR001",
    name: "North Cauvery Canal Plot A",
    surveyNumber: "Sy.No 142/3B",
    soilType: "Alluvial Clay Loam",
    coordinates: [
      [16.5124, 80.6982],
      [16.5138, 80.7015],
      [16.5109, 80.7028],
      [16.5095, 80.6995],
      [16.5124, 80.6982],
    ],
    centerLat: 16.5116,
    centerLng: 80.7005,
    approxAreaAcres: 2.35,
    registeredAt: "2026-05-28T08:30:00Z",
  },
  {
    id: "FL002",
    farmerId: "FMR001",
    name: "East Krishna Main Road Field",
    surveyNumber: "Sy.No 158/1A",
    soilType: "Black Cotton Soil",
    coordinates: [
      [16.521, 80.712],
      [16.5235, 80.7155],
      [16.5205, 80.717],
      [16.518, 80.7135],
      [16.521, 80.712],
    ],
    centerLat: 16.5208,
    centerLng: 80.7145,
    approxAreaAcres: 3.15,
    registeredAt: "2026-05-30T10:15:00Z",
  },
  {
    id: "FL003",
    farmerId: "FMR001",
    name: "South Pond Ridge",
    surveyNumber: "Sy.No 164/4",
    soilType: "Sandy Loam",
    coordinates: [
      [16.504, 80.691],
      [16.506, 80.6935],
      [16.5035, 80.695],
      [16.5015, 80.6925],
      [16.504, 80.691],
    ],
    centerLat: 16.5038,
    centerLng: 80.693,
    approxAreaAcres: 1.3,
    registeredAt: "2026-06-02T11:00:00Z",
  },
];

export const initialCrops: CropRecord[] = [
  {
    id: "CRP001",
    fieldId: "FL001",
    farmerId: "FMR001",
    cropType: "Rice",
    variety: "BPT 5204 (Samba Mahsuri)",
    sowingDate: "2026-06-10",
    expectedHarvestDate: "2026-11-15",
    currentStage: "Flowering",
    season: "Kharif 2026",
    cultivatedAreaAcres: 2.35,
  },
  {
    id: "CRP002",
    fieldId: "FL002",
    farmerId: "FMR001",
    cropType: "Cotton",
    variety: "Bt Cotton RCH-2",
    sowingDate: "2026-06-25",
    expectedHarvestDate: "2026-12-20",
    currentStage: "Vegetative Growth",
    season: "Kharif 2026",
    cultivatedAreaAcres: 3.15,
  },
  {
    id: "CRP003",
    fieldId: "FL003",
    farmerId: "FMR001",
    cropType: "Black Gram",
    variety: "LBG-752",
    sowingDate: "2026-07-05",
    expectedHarvestDate: "2026-10-10",
    currentStage: "Vegetative Growth",
    season: "Kharif 2026",
    cultivatedAreaAcres: 1.3,
  },
];

// High quality agricultural evidence photos (healthy lush paddy & flood inundation)
export const sampleCropImages = {
  healthyWide: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1000&q=80",
  healthyClose: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1000&q=80",
  healthyGrowth: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=1000&q=80",
  postDisasterWide: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80",
  postDisasterDamaged: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1000&q=80",
  postDisasterClose: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=1000&q=80",
  moderateLodging: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=1000&q=80",
};

export const initialEvidence: EvidenceRecord[] = [
  // 1. Sowing / Early Growth (Pre-disaster)
  {
    id: "EVD001",
    farmerId: "FMR001",
    fieldId: "FL001",
    cropId: "CRP001",
    imageUrl: sampleCropImages.healthyGrowth,
    lat: 16.5115,
    lng: 80.6995,
    timestamp: "2026-06-28T09:15:00Z",
    cropStage: "Vegetative Growth",
    evidenceType: "Growth",
    notes: "Healthy tillering after first organic fertilizer application.",
    damageClassification: "NONE",
    aiAssessment: {
      finalStatus: "VERIFIED EVIDENCE",
      evidenceType: "Growth",
      evidenceQuality: "HIGH",
      cropIdentified: "Rice (Paddy)",
      cropStage: "Vegetative Growth",
      observedConditions: "Vibrant vegetative tillers with uniform canopy greenness and standard row spacing.",
      detectedDamage: ["None"],
      damageSeverity: "NONE",
      confidence: 96,
      estimatedAffectedArea: "0%",
      evidenceMismatch: false,
      reason: "Excellent canopy density, intact root establishment, no discoloration or leaf burn observed.",
      humanReviewRequired: false,
      analyzedAt: "2026-06-28T09:20:00Z",
    },
    verification: {
      gpsPassed: true,
      gpsDistanceMeters: 45,
      timestampPassed: true,
      duplicatePassed: true,
      weatherCorrelationPassed: true,
      timelinePassed: true,
      overallStatus: "Passed",
      checkedAt: "2026-06-28T09:25:00Z",
    },
  },
  // 2. Pre-disaster baseline (Flowering stage baseline)
  {
    id: "EVD002",
    farmerId: "FMR001",
    fieldId: "FL001",
    cropId: "CRP001",
    imageUrl: sampleCropImages.healthyWide,
    lat: 16.5121,
    lng: 80.7008,
    timestamp: "2026-08-15T08:45:00Z",
    cropStage: "Flowering",
    evidenceType: "Pre-disaster",
    stepName: "Pre-Disaster Baseline Record",
    notes: "Crop reaching panicle initiation and flowering stage. Healthy crop stand.",
    damageClassification: "NONE",
    aiAssessment: {
      finalStatus: "VERIFIED EVIDENCE",
      evidenceType: "Pre-disaster",
      evidenceQuality: "HIGH",
      cropIdentified: "Rice (Paddy)",
      cropStage: "Flowering",
      observedConditions: "Lush green panicle emergence with healthy erect flag leaves.",
      detectedDamage: ["None"],
      damageSeverity: "NONE",
      estimatedAffectedArea: "0%",
      evidenceMismatch: false,
      confidence: 97,
      reason: "Pre-disaster baseline confirms normal crop stand with zero waterlogging or pest stress.",
      humanReviewRequired: false,
      analyzedAt: "2026-08-15T08:50:00Z",
    },
    verification: {
      gpsPassed: true,
      gpsDistanceMeters: 30,
      timestampPassed: true,
      duplicatePassed: true,
      weatherCorrelationPassed: true,
      timelinePassed: true,
      overallStatus: "Passed",
      checkedAt: "2026-08-15T08:55:00Z",
    },
  },
  // 3. Post-disaster Guided Step 1: Wide field view
  {
    id: "EVD003",
    farmerId: "FMR001",
    fieldId: "FL001",
    cropId: "CRP001",
    imageUrl: sampleCropImages.postDisasterWide,
    lat: 16.5126,
    lng: 80.6998,
    timestamp: "2026-08-23T10:10:00Z",
    cropStage: "Flowering",
    evidenceType: "Wide field view",
    stepName: "Step 1: Wide field view",
    notes: "Entire northern quadrant inundated following torrential flash rain and canal breach.",
    damageClassification: "SEVERE",
    aiAssessment: {
      finalStatus: "VERIFIED EVIDENCE",
      evidenceType: "Wide field view",
      evidenceQuality: "MEDIUM",
      cropIdentified: "Rice (Paddy)",
      cropStage: "Flowering",
      observedConditions: "Extensive standing flood water covering ~70% of field surface with submerged panicles.",
      detectedDamage: ["Canopy submergence", "Extensive water pooling", "Silt deposition"],
      damageSeverity: "SEVERE",
      estimatedAffectedArea: "70%",
      evidenceMismatch: false,
      confidence: 94,
      reason: "Severe field inundation with floodwater depth exceeding 40cm, causing canopy submergence.",
      humanReviewRequired: true,
      analyzedAt: "2026-08-23T10:15:00Z",
    },
    verification: {
      gpsPassed: true,
      gpsDistanceMeters: 55,
      timestampPassed: true,
      duplicatePassed: true,
      weatherCorrelationPassed: true,
      timelinePassed: true,
      overallStatus: "Passed",
      checkedAt: "2026-08-23T10:20:00Z",
    },
  },
  // 4. Post-disaster Guided Step 2: Section view
  {
    id: "EVD004",
    farmerId: "FMR001",
    fieldId: "FL001",
    cropId: "CRP001",
    imageUrl: sampleCropImages.moderateLodging,
    lat: 16.5108,
    lng: 80.7018,
    timestamp: "2026-08-23T10:25:00Z",
    cropStage: "Flowering",
    evidenceType: "Post-disaster",
    stepName: "Step 2: Section view",
    notes: "Eastern section showing lodging from heavy wind gusts.",
    damageClassification: "MODERATE",
    aiAssessment: {
      finalStatus: "VERIFIED EVIDENCE",
      evidenceType: "Post-disaster",
      evidenceQuality: "HIGH",
      cropIdentified: "Rice (Paddy)",
      cropStage: "Flowering",
      observedConditions: "Moderate stalk lodging (approx 45-degree tilt) with damp foliage.",
      detectedDamage: ["Canopy tilt/lodging", "Moderate leaf tearing", "Root-zone soil saturation"],
      damageSeverity: "MODERATE",
      estimatedAffectedArea: "40%",
      evidenceMismatch: false,
      confidence: 91,
      reason: "Wind-induced crop lodging across eastern plot; stalks partially erect but root anchoring strained.",
      humanReviewRequired: true,
      analyzedAt: "2026-08-23T10:30:00Z",
    },
    verification: {
      gpsPassed: true,
      gpsDistanceMeters: 62,
      timestampPassed: true,
      duplicatePassed: true,
      weatherCorrelationPassed: true,
      timelinePassed: true,
      overallStatus: "Passed",
      checkedAt: "2026-08-23T10:35:00Z",
    },
  },
  // 5. Post-disaster Guided Step 3: Damaged area
  {
    id: "EVD005",
    farmerId: "FMR001",
    fieldId: "FL001",
    cropId: "CRP001",
    imageUrl: sampleCropImages.postDisasterDamaged,
    lat: 16.5112,
    lng: 80.7001,
    timestamp: "2026-08-23T10:40:00Z",
    cropStage: "Flowering",
    evidenceType: "Damaged area",
    stepName: "Step 3: Severely damaged area",
    notes: "Center depressed patch where floodwater accumulated and flattened plants completely.",
    damageClassification: "SEVERE",
    aiAssessment: {
      finalStatus: "VERIFIED EVIDENCE",
      evidenceType: "Damaged area",
      evidenceQuality: "HIGH",
      cropIdentified: "Rice (Paddy)",
      cropStage: "Flowering",
      observedConditions: "Complete crop lodging with plants submerged under muddy flood silt.",
      detectedDamage: ["Total stalk lodging", "Mud silt accumulation", "Panicle rot risk"],
      damageSeverity: "SEVERE",
      estimatedAffectedArea: "100%",
      evidenceMismatch: false,
      confidence: 95,
      reason: "Total canopy flattening and grain panicle submergence leading to severe anoxic rot risk.",
      humanReviewRequired: true,
      analyzedAt: "2026-08-23T10:45:00Z",
    },
    verification: {
      gpsPassed: true,
      gpsDistanceMeters: 20,
      timestampPassed: true,
      duplicatePassed: true,
      weatherCorrelationPassed: true,
      timelinePassed: true,
      overallStatus: "Passed",
      checkedAt: "2026-08-23T10:50:00Z",
    },
  },
  // 6. Post-disaster Guided Step 4: Close-up view
  {
    id: "EVD006",
    farmerId: "FMR001",
    fieldId: "FL001",
    cropId: "CRP001",
    imageUrl: sampleCropImages.postDisasterClose,
    lat: 16.5118,
    lng: 80.7004,
    timestamp: "2026-08-23T10:55:00Z",
    cropStage: "Flowering",
    evidenceType: "Close-up",
    stepName: "Step 4: Close-up of crop foliage",
    notes: "Close up of discolored and torn leaf blades soaked in rainwater.",
    damageClassification: "MODERATE",
    aiAssessment: {
      finalStatus: "VERIFIED EVIDENCE",
      evidenceType: "Close-up",
      evidenceQuality: "HIGH",
      cropIdentified: "Rice (Paddy)",
      cropStage: "Flowering",
      observedConditions: "Leaf blade laceration, water soak lesions, and beginning chlorosis on submerged foliage.",
      detectedDamage: ["Leaf tip necrosis", "Waterlogging lesions", "Silt coated flag leaf"],
      damageSeverity: "MODERATE",
      estimatedAffectedArea: "50%",
      evidenceMismatch: false,
      confidence: 92,
      reason: "Micro-inspection shows leaf tip necrosis from continuous 48-hour moisture saturation.",
      humanReviewRequired: true,
      analyzedAt: "2026-08-23T11:00:00Z",
    },
    verification: {
      gpsPassed: true,
      gpsDistanceMeters: 25,
      timestampPassed: true,
      duplicatePassed: true,
      weatherCorrelationPassed: true,
      timelinePassed: true,
      overallStatus: "Passed",
      checkedAt: "2026-08-23T11:05:00Z",
    },
  },
];

export const initialDisasterReports: DisasterReport[] = [
  {
    id: "DR001",
    fieldId: "FL001",
    cropId: "CRP001",
    farmerId: "FMR001",
    disasterType: "Heavy Rainfall",
    date: "2026-08-22",
    time: "14:30",
    description: "Continuous unseasonal cloudburst and heavy downpour for 18 hours causing overflow from the adjoining canal into field FL001.",
    photoUrl: sampleCropImages.postDisasterWide,
    status: "Under Review",
    reportedAt: "2026-08-22T16:00:00Z",
    weatherAnomalyConfirmed: true,
  },
];

export const initialClaims: ClaimRecord[] = [
  {
    id: "CLM-AP-2026-001",
    disasterReportId: "DR001",
    farmerId: "FMR001",
    fieldId: "FL001",
    cropId: "CRP001",
    status: "Under Review",
    claimDate: "2026-08-23",
    disasterType: "Heavy Rainfall",
    evidenceCompleteness: 100,
    preliminaryLossEstimate: {
      fieldAreaAcres: 2.35,
      estimatedDamagePercent: 68,
      estimatedAffectedAcres: 1.6,
      sumInsuredPerAcreINR: 38500,
      estimatedLossAmountINR: 61600,
    },
    aiDamageAggregate: {
      healthyPercent: 32,
      moderatePercent: 28,
      severePercent: 40,
      estimatedDamagePercent: 68,
      totalImagesAnalyzed: 4,
    },
  },
];

